// <auto-generated />
using System;
using ExcelSF.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using AppContext = ExcelSF.DataBase.AppContext;

#nullable disable

namespace ExcelSF.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ExcelSF.Models.Autorizacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<long>("IdGerente1")
                        .HasColumnType("bigint");

                    b.Property<long>("IdGerente2")
                        .HasColumnType("bigint");

                    b.Property<string>("ObservacaoFuncionario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacaoGerente1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacaoGerente2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatusGerente1")
                        .HasColumnType("bit");

                    b.Property<bool>("StatusGerente2")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Autorizacao");
                });

            modelBuilder.Entity("ExcelSF.Models.Cargo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cargo");
                });

            modelBuilder.Entity("ExcelSF.Models.Contrato", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("CargoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<double>("Salario")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.ToTable("Contrato");
                });

            modelBuilder.Entity("ExcelSF.Models.Endereco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("CEP")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Longadouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("NumeroCasa")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("ExcelSF.Models.Ferias", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("AdiantamentoDecimoTerceiro")
                        .HasColumnType("bit");

                    b.Property<bool>("AutorizacaoGerente1")
                        .HasColumnType("bit");

                    b.Property<bool>("AutorizacaoGerente2")
                        .HasColumnType("bit");

                    b.Property<long?>("AutorizacaoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataFim2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio2")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<long?>("HistoricoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PeriodoAquisitivoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AutorizacaoId");

                    b.HasIndex("HistoricoId");

                    b.HasIndex("PeriodoAquisitivoId");

                    b.ToTable("Ferias");
                });

            modelBuilder.Entity("ExcelSF.Models.Funcionario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CPF")
                        .HasColumnType("bigint");

                    b.Property<long?>("ContratoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<long?>("EnderecoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FeriasId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<long?>("TelefoneId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.HasIndex("EnderecoId");

                    b.HasIndex("FeriasId");

                    b.HasIndex("TelefoneId");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("ExcelSF.Models.Historico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<long>("QuantidadeDeDias")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UltimoPeriodo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Venda")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Historico");
                });

            modelBuilder.Entity("ExcelSF.Models.PeriodoAquisitivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DataDaContratacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UltimoPeriodo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PeriodoAquisitivo");
                });

            modelBuilder.Entity("ExcelSF.Models.Telefone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("ExcelSF.Models.Contrato", b =>
                {
                    b.HasOne("ExcelSF.Models.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId");

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("ExcelSF.Models.Ferias", b =>
                {
                    b.HasOne("ExcelSF.Models.Autorizacao", "Autorizacao")
                        .WithMany()
                        .HasForeignKey("AutorizacaoId");

                    b.HasOne("ExcelSF.Models.Historico", "Historico")
                        .WithMany()
                        .HasForeignKey("HistoricoId");

                    b.HasOne("ExcelSF.Models.PeriodoAquisitivo", "PeriodoAquisitivo")
                        .WithMany()
                        .HasForeignKey("PeriodoAquisitivoId");

                    b.Navigation("Autorizacao");

                    b.Navigation("Historico");

                    b.Navigation("PeriodoAquisitivo");
                });

            modelBuilder.Entity("ExcelSF.Models.Funcionario", b =>
                {
                    b.HasOne("ExcelSF.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId");

                    b.HasOne("ExcelSF.Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId");

                    b.HasOne("ExcelSF.Models.Ferias", "Ferias")
                        .WithMany()
                        .HasForeignKey("FeriasId");

                    b.HasOne("ExcelSF.Models.Telefone", "Telefone")
                        .WithMany()
                        .HasForeignKey("TelefoneId");

                    b.Navigation("Contrato");

                    b.Navigation("Endereco");

                    b.Navigation("Ferias");

                    b.Navigation("Telefone");
                });
#pragma warning restore 612, 618
        }
    }
}
